/*
 * The Hunger Games Simulator - event content.
 *
 * Event shape:  { n: tributes involved, t: text, k: killer slots, d: dead slots, c: cause of death }
 *   {0} {1} {2} in text/cause are replaced by the tributes' names.
 *   k = indexes of tributes who get credit for the kill(s)
 *   d = indexes of tributes who die in the event
 *
 * Helpers:  N(n, text) harmless  |  D(text, cause) solo death  |  K(n, text, killers, dead, cause)
 * Everything is written pronoun-free (names / "they") so it works for any tribute.
 *
 * Special flags:  F = forms an alliance ({a} = new alliance name)  |  A = needs allies together  |
 *                 B = betrayal, killer and victim are allies  |  AD = an ally dies saving another
 * Arena rules of thumb: an ABANDONED butterfly pavilion, overgrown. The center is the Cornucopia. The butterflies are
 * KILLERS. Many plants are poisonous. Still water holds brain-eating amoeba. Barrels and rocks are radioactive.
 * Loot: white liquor, brown liquor, a brick, a feline familiar, a really good shoe, gas masks, radon, lots of ibuprofen.
 */
(function (global) {
  const N = (n, t) => ({ n, t, k: [], d: [] });
  const K = (n, t, k, d, c) => ({ n, t, k, d, c });
  const D = (t, c) => ({ n: 1, t, k: [], d: [0], c });
  const F = (n, t) => ({ n, t, k: [], d: [], form: true });
  const A = (n, t) => ({ n, t, k: [], d: [], ally: true });
  const AD = (n, t, c) => ({ n, t, k: [], d: [0], c, ally: true });
  const B = (n, t, k, d, c) => ({ n, t, k, d, c, betray: true });

  /* ---------------------------------------------------------------- BLOODBATH */
  const bloodbath = [
    N(1, `{0} grabs a backpack from the Cornucopia and sprints into the trees.`),
    N(1, `{0} grabs a jug of white liquor and hugs it like a newborn.`),
    N(1, `{0} grabs a brick. Just a brick. They look immensely pleased.`),
    N(1, `{0} snags a really good shoe. One shoe. It is a truly excellent shoe.`),
    N(1, `{0} grabs a bottle of brown liquor and bolts, whispering "mine."`),
    N(1, `{0} grabs a sleeping bag and a feline familiar, who immediately claws their face. Love at first bite.`),
    N(1, `{0} sprints away from the Cornucopia screaming before anyone has done anything.`),
    N(1, `{0} dives into a bush and stays there until the first cannon fires.`),
    N(1, `{0} stays on the platform for a full minute doing math. The math says "run".`),
    N(1, `{0} grabs a bow, then realizes they have no idea what a bow is for.`),
    N(1, `{0} runs off with a bag of apples and a very smug expression.`),
    N(2, `{0} and {1} fight over a really good shoe. {1} wins; {0} limps away wearing one regular shoe.`),
    F(2, `{0} and {1} form an alliance over a shared love of white liquor. They call themselves "{a}".`),
    N(2, `{0} and {1} both grab the same brick and have a very awkward standoff. Both walk away with half a brick.`),
    F(3, `{0}, {1} and {2} form an alliance at the Cornucopia. They name it "{a}".`),
    F(2, `{0} and {1} lock eyes across the Cornucopia, both holding bricks, and decide to be friends. "{a}" is born.`),
    N(1, `{0} grabs a gas mask and puts it on immediately. They are now the most terrifying person in the arena.`),
    N(1, `{0} grabs an enormous bottle of ibuprofen. Pain is no longer a concern.`),
    N(1, `{0} grabs a canister labeled "RADON: HANDLE WITH CARE" and handles it with care.`),
    N(1, `{0} grabs a Geiger counter and a gas mask. The counter immediately starts to scream.`),
    D(`{0} grabs a canister at the Cornucopia and sniffs it. It is radon. It was clearly labeled radon.`, `Radon exposure (sniffed a canister at the Cornucopia)`),
    D(`{0} steps off their platform too early and is blown to bits.`, `Stepped off the platform early (landmine)`),
    D(`{0} drinks white liquor straight from the Cornucopia at the gong and face-plants into a rake.`, `Drunken face-plant into a rake`),
    D(`{0} grabs the shiniest thing in the Cornucopia. It was a trap. It was always a trap.`, `Shiny-object trap`),
    K(2, `{0} throws a brick at {1}. A single, perfect brick.`, [0], [1], `Bricked by {0}`),
    K(2, `{0} stabs {1} with a machete.`, [0], [1], `Machete, courtesy of {0}`),
    K(2, `{0} skewers {1} with a spear as they flee.`, [0], [1], `Speared by {0}`),
    K(2, `{0} knocks out {1} with a really good shoe. A VERY good shoe.`, [0], [1], `Struck with a really good shoe by {0}`),
    K(2, `{0} bonks {1} with a bottle of brown liquor. The bottle does not break. {1} does.`, [0], [1], `Brown liquor bottle to the head ({0})`),
    K(2, `{0} releases a feline familiar onto {1}'s face. {1} is not seen again.`, [0], [1], `Feline familiar to the face (sent by {0})`),
    K(2, `{0} strangles {1} with a backpack strap.`, [0], [1], `Strangled by {0}`),
    K(3, `{0} and {1} corner {2} behind the Cornucopia.`, [0, 1], [2], `Cornered at the Cornucopia by {0} and {1}`),
    K(2, `{0} and {1} are both drunk by the first minute and kill each other with bricks.`, [], [0, 1], `Mutual bricking (drunk at the Cornucopia)`),
  ];

  /* ---------------------------------------------------------------- SHARED (day + night) */
  const any = [
    N(1, `{0} makes a spear from a stick and feels like a god.`),
    N(1, `{0} befriends a feline familiar and names it Gary.`),
    N(1, `{0} spends an hour trying to start a fire and gets a very good blister instead.`),
    N(1, `{0} finds a stream and drinks deeply. Thankfully, it is not toxic.`),
    N(1, `{0} tells themself "I am a survivor" forty times into a puddle.`),
    N(1, `{0} wears a really good shoe on one foot and protects the other with a leaf.`),
    N(1, `{0} spots a killer butterfly from a safe distance. It stares back with menace.`),
    N(1, `{0} builds a lean-to out of branches. It is mostly leaves.`),
    N(1, `{0} correctly identifies an edible berry. A small triumph.`),
    N(1, `{0} carves their name into a tree, then regrets it. Now everyone knows where they are.`),
    N(1, `{0} cries over a rock they have befriended.`),
    N(1, `{0} hears a cannon and wonders who it was. Then remembers that it was not them.`),
    N(1, `{0} sharpens a stick, then drops it because splinter.`),
    N(1, `{0} uses a brick as a pillow and has the best sleep of their life.`),
    N(1, `{0} trips over their own really good shoe and gets back up like nothing happened.`),
    N(1, `{0} fights their own reflection in a pond. It's a draw.`),
    N(1, `{0} declares themself "Mayor of this tree". Nobody votes.`),
    N(1, `{0} drinks white liquor and challenges a tree to a fight. The tree doesn't respond. {0} claims victory.`),
    N(1, `{0} drinks brown liquor and delivers a heartfelt speech to a squirrel. The squirrel nods.`),
    N(1, `{0} drinks white liquor and falls asleep standing up.`),
    N(1, `{0} drinks white liquor and sings the national anthem at full volume. Every tribute now knows exactly where they are. {0} is, mercifully, not found.`),
    N(1, `{0} drinks brown liquor and is 100% certain they can fly. They do not try. Today.`),
    N(1, `{0} gets so drunk they forget they are in the Hunger Games and apologize to a bush.`),
    N(1, `{0} drunkenly tells their feline familiar their deepest secrets. The cat is unmoved.`),
    N(1, `{0} loses a really good shoe, finds it, loses it, finds it, loses it, and cries.`),
    N(1, `{0} throws a brick in the air to see what happens. It comes down. Nobody is there. Phew.`),
    N(2, `{0} and {1} share brown liquor and promise to be friends forever. They are both lying.`),
    N(2, `{0} and {1} trade a brick for a really good shoe. Both feel they got the better deal.`),
    N(2, `{0} teaches {1} to tell safe berries from poisonous ones. {1} listens to none of it.`),
    N(2, `{0} and {1} spot each other and both decide to run in opposite directions.`),
    N(2, `{0} and {1} hold a funeral for a butterfly that was, in fact, trying to kill them.`),
    N(2, `{0} and {1} take turns holding the really good shoe.`),
    N(3, `{0}, {1} and {2} sit around a fire, swapping rumors about the Gamemakers.`),
    D(`{0} eats a handful of bright purple berries. They were extremely poisonous. So was the second handful.`, `Poisonous berries (two handfuls)`),
    D(`{0} sniffs a beautiful glowing flower. It exhales back.`, `Inhaled a poisonous flower`),
    D(`{0} makes tea from leaves that look like mint. They are not mint.`, `Poisonous "mint" tea`),
    D(`{0} leans against a tree covered in oozing sap. It is a manchineel. It is the last tree they will ever lean on.`, `Poisonous manchineel tree`),
    D(`{0} uses a fuzzy leaf as a bandage. The leaf is deadly.`, `Poisonous leaf bandage`),
    D(`{0} bends over to smell a carnivorous flower. It is hungry.`, `Eaten by a carnivorous plant`),
    D(`{0} licks a bright blue frog to see what happens.`, `Licked a poison dart frog`),
    D(`{0} is delighted by a gorgeous butterfly. The butterfly has razor wings. The delight is brief.`, `Sliced by a razorwing butterfly`),
    D(`{0} reaches out to pet a butterfly resting on a flower. The rest of the flock was also resting on the flower.`, `Killer butterfly swarm`),
    D(`{0} swats at a butterfly. In response, the entire flock descends.`, `Provoked a killer butterfly flock`),
    D(`{0} follows a pretty butterfly into a swamp. It was leading them somewhere.`, `Lured into quicksand by a killer butterfly`),
    D(`{0} drinks far too much white liquor and falls over. Permanently.`, `Fell over after too much white liquor`),
    D(`{0} drinks brown liquor, decides they can swim across the river, and cannot.`, `Drunken river swim`),
    D(`{0} gets drunk and picks a fight with a bear. The bear was a bear.`, `Drunkenly fought a bear`),
    D(`{0} drinks something from an unlabeled jug. It is lamp oil. Then they light a campfire.`, `Lamp-oil campfire explosion`),
    D(`{0} throws a brick straight up to see if it will come back down. It does.`, `Hit by their own brick`),
    D(`{0} puts on a really good shoe, trips over the laces, and falls into a ravine.`, `Tripped over a really good shoe`),
    D(`{0} saws off the branch they are sitting on, in a move that surprises nobody.`, `Sawed off the branch they were sitting on`),
    D(`{0} yells "I'M THE BEST ONE HERE" at the sky and is immediately struck by lightning.`, `Lightning (shouted a challenge to the sky)`),
    D(`{0} falls asleep with their feline familiar sitting on their face. Cats love you to death.`, `Smothered by a feline familiar's affection`),
    K(2, `{0} challenges {1} to a drinking contest. {1} loses, in the permanent way.`, [0], [1], `Lost a drinking contest to {0} (alcohol poisoning)`),
    K(2, `{0} offers {1} some free "samples" of berries. They are poisonous.`, [0], [1], `Fed poisonous berries by {0}`),
    K(2, `{0} offers {1} a swig of brown liquor. It was poisoned.`, [0], [1], `Poisoned brown liquor served by {0}`),
    K(2, `{0} ties {1} to a tree swarming with killer butterflies.`, [0], [1], `Fed to the killer butterflies by {0}`),
    K(2, `{0} sets a snare. {1} walks right into it.`, [0], [1], `Snared by {0}'s trap`),
    K(2, `{0} throws a brick at {1}'s head from forty feet away. Nobody is more surprised than {0}.`, [0], [1], `Long-distance bricking by {0}`),
    K(2, `{0} pushes {1} off a cliff.`, [0], [1], `Pushed off a cliff by {0}`),
    K(2, `{0} throws a knife at {1}.`, [0], [1], `Knife, thrown by {0}`),
    K(2, `{0} sends their feline familiar after {1}. It is extremely effective.`, [0], [1], `Feline familiar attack (sent by {0})`),
    K(3, `{0} and {1} ambush {2}, who was distracted by a particularly handsome butterfly.`, [0, 1], [2], `Ambushed by {0} and {1}`),
    N(5, `{0}, {1}, {2}, {3} and {4} share one can of beans in an uneasy truce. It is a very good can of beans.`),
    N(4, `{0}, {1}, {2} and {3} all try to hide behind the same tree from a razorwing swarm. It is a very small tree. Everyone survives, barely.`),
    N(4, `{0}, {1}, {2} and {3} meet at a watering hole, stare at each other for ten minutes, and back away in four different directions.`),
    K(4, `{0} and {1} corner {2} and {3} at a pond. A brawl erupts; {2} is shoved in and gets an amoeba. {3} flees.`, [0, 1], [2], `Brain-eating amoeba (brawl at the pond)`),
    K(5, `Five tributes reach the same watering hole. Everyone is armed. Everyone is tired. {0}, {1}, {2} and {3} all attack {4} at once. It isn't even fair.`, [0, 1, 2, 3], [4], `Mobbed at the watering hole by {0}, {1}, {2} and {3}`),
    K(3, `{0}, {1} and {2} drink all the white liquor, form a conga line, and dance straight off a cliff.`, [], [0, 1, 2], `Drunken conga line off a cliff`),
    K(2, `{0} and {1} get into a fistfight over a really good shoe. Both tumble off a cliff.`, [], [0, 1], `Fell off a cliff fighting over a really good shoe`),
    K(2, `{0} and {1} decide to settle it with a brick-throwing contest. Both bricks land on the opposite tribute.`, [], [0, 1], `Simultaneous bricking`),
  ];

  /* ---------------------------------------------------------------- CLASSIC FATAL EVENTS (shared by every phase) */
  const classic = [
    K(2, `{0} throws a knife into {1}'s head.`, [0], [1], `Knife to the head, thrown by {0}`),
    K(2, `{0} throws a knife into {1}'s chest.`, [0], [1], `Knife to the chest, thrown by {0}`),
    K(2, `{0} shoots an arrow into {1}'s head.`, [0], [1], `Arrow to the head, shot by {0}`),
    K(2, `{0} catches {1} off guard and kills them.`, [0], [1], `Caught off guard and killed by {0}`),
    K(2, `{0} stabs {1} while their back is turned.`, [0], [1], `Stabbed in the back by {0}`),
    K(2, `{0} bashes {1}'s head against a rock several times.`, [0], [1], `Head bashed against a rock by {0}`),
    K(2, `{0} bashes {1}'s head in with a mace.`, [0], [1], `Mace to the head, courtesy of {0}`),
    K(2, `{0} snaps {1}'s neck.`, [0], [1], `Neck snapped by {0}`),
    K(2, `{0} decapitates {1} with a sword.`, [0], [1], `Decapitated by {0}`),
    K(2, `{0} spears {1} in the abdomen.`, [0], [1], `Speared by {0}`),
    K(2, `{0} sets {1} on fire with a molotov.`, [0], [1], `Burned by {0}'s molotov`),
    K(2, `{0} kills {1} with a hatchet.`, [0], [1], `Hatchet, wielded by {0}`),
    K(2, `{0} kills {1} with their own weapon.`, [0], [1], `Killed with their own weapon by {0}`),
    K(2, `{0} overpowers {1}, killing them.`, [0], [1], `Overpowered by {0}`),
    K(2, `{0} kills {1} as they try to run.`, [0], [1], `Killed by {0} while trying to run`),
    K(2, `{0} pushes {1} off a cliff during a knife fight.`, [0], [1], `Pushed off a cliff by {0} during a knife fight`),
    K(2, `{0} severely injures {1}, but puts them out of their misery.`, [0], [1], `Injured and then finished off by {0}`),
    K(2, `{0} severely injures {1} and leaves them to die.`, [0], [1], `Injured and left to die by {0}`),
    K(2, `{0} is unable to convince {1} not to kill them.`, [1], [0], `Killed by {1} after a failed plea for mercy`),
    K(2, `{0} convinces {1} not to kill them, only to kill {1} instead.`, [0], [1], `Talked into a trap by {0}`),
    K(2, `{0} sets an explosive off, killing {1}.`, [0], [1], `Blown up by {0}`),
    K(3, `{0} sets an explosive off, killing {1} and {2}.`, [0], [1, 2], `Blown up by {0}`),
    K(4, `{0} sets an explosive off, killing {1}, {2} and {3}.`, [0], [1, 2, 3], `Blown up by {0}`),
    K(3, `{0} and {1} work together to drown {2}.`, [0, 1], [2], `Drowned by {0} and {1}`),
    K(3, `{0}, {1} and {2} start fighting, but {1} runs away as {0} kills {2}.`, [0], [2], `Killed in a three-way fight by {0}`),
    K(3, `{0} attacks {1}, but {2} protects them, killing {0}.`, [2], [0], `Killed by {2} while attacking {1}`),
    K(4, `{0} and {1} fight {2} and {3}. {0} and {1} survive.`, [0, 1], [2, 3], `Lost a two-on-two fight to {0} and {1}`),
    K(4, `{0} and {1} fight {2} and {3}. {2} and {3} survive.`, [2, 3], [0, 1], `Lost a two-on-two fight to {2} and {3}`),
    D(`{0} accidentally steps on a landmine.`, `Stepped on a landmine`),
    D(`{0} falls into a pit and dies.`, `Fell into a pit`),
    D(`{0} falls through the rotten glass floor of the old koi pond and drowns.`, `Drowned in the old koi pond`),
  ];

  /* ---------------------------------------------------------------- HAZARDS (abandoned pavilion, amoeba, radiation) */
  const hazards = [
    N(1, `{0} explores the abandoned pavilion and finds a faded sign: "PLEASE DO NOT FEED THE BUTTERFLIES". The sign has claw marks.`),
    N(1, `{0} wanders under the pavilion's shattered glass dome. The butterflies are still here. The glass is not.`),
    N(1, `{0} finds an empty terrarium labeled "DO NOT OPEN". It's open. That's the scary part.`),
    N(1, `{0} reads a rotted plaque: "Butterflies are our friends." Somebody has crossed out "friends."`),
    N(1, `{0} sees a still, green pond and, for the first time in their life, listens to their gut and walks away.`),
    N(1, `{0} finds a Geiger counter. It clicks. And clicks. And does not stop clicking. {0} keeps it anyway.`),
    N(1, `{0} walks past a barrel marked with a trefoil. Nope.`),
    N(1, `{0} finds a glowing green rock and decides, wisely, not to put it in their pocket.`),
    N(1, `{0}'s hair begins falling out in clumps. They blame stress.`),
    N(1, `{0} notices their skin glowing faintly in the dark. They will be very easy to find tonight.`),
    N(1, `{0} finds a gas mask and wears it all day. Nobody can tell if they are a friend or a foe.`),
    N(1, `{0} puts on a gas mask and announces, in a muffled voice, that they are "the dad now."`),
    N(1, `{0} finds a bottle of ibuprofen and takes two for a headache. A careful, sensible hero.`),
    N(1, `{0} takes ibuprofen for every pain: radiation sickness, a sprained ankle, a broken heart. It mostly works.`),
    N(1, `{0} makes a necklace out of ibuprofen tablets. Fashionable. Medicinal.`),
    N(1, `{0} carries a canister of radon around like a trophy. Everyone keeps their distance. It works as a weapon.`),
    N(1, `{0} boils water for ten minutes, just in case. It was a good idea.`),
    N(2, `{0} and {1} take turns wearing the only gas mask.`),
    N(2, `{0} and {1} share a bottle of ibuprofen and complain about their headaches together.`),
    N(2, `{0} and {1} argue about whether the green glow is "bad" or "just a vibe". Both agree to avoid it.`),
    D(`{0} splashes water from a warm, still pond onto their face. A tiny amoeba finds a new home in their brain.`, `Brain-eating amoeba (warm, still water)`),
    D(`{0} rinses their nose with water from a stagnant fountain. This is a bad decision with a very short consequence.`, `Brain-eating amoeba (stagnant fountain)`),
    D(`{0} uses a neti pot filled with pond water. Ten minutes later: headache. Twenty: confusion. Thirty: the cannon.`, `Brain-eating amoeba (neti pot of pond water)`),
    D(`{0} jumps into a warm, still pool for a swim and surfaces with a smile and an amoeba.`, `Brain-eating amoeba (swim in a still pool)`),
    D(`{0} puts a glowing green rock in their pocket as a lucky charm. It is not lucky.`, `Radiation poisoning (lucky rock)`),
    D(`{0} drinks from a glowing puddle because "it probably has electrolytes."`, `Radiation poisoning (drank from a glowing puddle)`),
    D(`{0} camps beside a barrel marked with a trefoil. They wake up with no hair and no future.`, `Radiation poisoning (camped by a barrel)`),
    D(`{0} eats berries from a bush so green it looks neon. They glow, and then they go.`, `Radiation poisoning (neon berries)`),
    D(`{0} cuddles a barrel of nuclear waste for warmth. It is warm.`, `Radiation poisoning (cuddled a barrel)`),
    D(`{0} takes eight ibuprofen for a headache. Then another eight. Then the whole bottle.`, `Ibuprofen overdose`),
    D(`{0} reads "take two ibuprofen" and takes two hundred.`, `Ibuprofen overdose (misread the label)`),
    D(`{0} finds a canister of radon and takes a curious sniff.`, `Radon exposure (curious sniff)`),
    D(`{0} sleeps in a cozy basement. It has radon. It has a lot of radon.`, `Radon exposure (cozy basement)`),
    D(`{0} takes off their gas mask "to get a better look". They get a better look.`, `Took off their gas mask in the toxic fog`),
    K(2, `{0} throws a canister of radon at {1}. A rare, unfriendly gift.`, [0], [1], `Radon canister thrown by {0}`),
    K(2, `{0} shoves {1} into a still, green pond and holds them under. The amoebae do the rest.`, [0], [1], `Brain-eating amoeba (dunked by {0})`),
    K(2, `{0} tricks {1} into taking off their gas mask.`, [0], [1], `Gas mask removed by trickery ({0})`),
    K(2, `{0} gives {1} a "lucky rock". It is radioactive.`, [0], [1], `Radiation poisoning (lucky rock from {0})`),
    K(2, `{0} gives {1} a bottle labeled "ibuprofen". It is not ibuprofen.`, [0], [1], `Fake ibuprofen from {0}`),
    K(2, `{0} locks {1} in the pavilion's old radon cellar.`, [0], [1], `Locked in a radon cellar by {0}`),
  ];

  /* ---------------------------------------------------------------- ALLIANCES */
  const alliances = [
    F(2, `{0} and {1} shake hands and form an alliance: "{a}". It will not end well.`),
    F(2, `{0} and {1} bond over a shared hatred of the Gamemakers. "{a}" is born.`),
    F(2, `{0} offers {1} half a bottle of white liquor for an alliance. {1} agrees. "{a}" is formed, and so are their headaches.`),
    F(3, `{0}, {1} and {2} team up as "{a}". They have a secret handshake. It is very, very long.`),
    F(3, `{0}, {1} and {2} form "{a}" over a shared bottle of brown liquor.`),
    F(2, `{0} and {1} agree to watch each other's backs. "{a}" is sealed with a fist bump and a brick.`),
    F(4, `{0}, {1}, {2} and {3} form "{a}" and agree to split the ibuprofen four ways.`),
    A(2, `{0} and {1} of "{a}" share their ibuprofen and complain about headaches together.`),
    A(2, `{0} and {1} of "{a}" take turns wearing the only gas mask.`),
    A(2, `{0} warns {1} of "{a}" about a green pond. "Don't. It looks like soup. It is not soup."`),
    A(2, `{0} and {1} of "{a}" argue over the last bottle of brown liquor, then decide to share. It's what allies do.`),
    A(2, `{0} saves {1} of "{a}" from a razorwing swarm. {1} owes them one really good shoe.`),
    A(2, `{0} and {1} of "{a}" swap stories about home and cry a little.`),
    A(3, `{0}, {1} and {2} of "{a}" argue over who gets the brick, then decide the brick belongs to the alliance.`),
    A(3, `{0}, {1} and {2} of "{a}" sleep in shifts. {2} sleeps through all of theirs.`),
    AD(2, `{0} shields {1} of "{a}" from a razorwing swarm and does not make it. {1} survives, covered in guilt and glitter.`, `Died saving their ally {1} from a razorwing swarm`),
    AD(2, `{0} pushes {1} of "{a}" out of the way of a falling tree and is not as lucky.`, `Crushed by a tree while saving their ally {1}`),
    AD(3, `{0} volunteers to taste-test a berry for "{a}". {1} and {2} watch in silence.`, `Poisonous berry taste-test (for "{a}")`),
    B(2, `{0} betrays {1} of "{a}" with a brick. The alliance is... less.`, [0], [1], `Betrayed by their ally {0} ("{a}")`),
    B(2, `{0} sells out {1} of "{a}" for a really good shoe.`, [0], [1], `Sold out by their ally {0} for a really good shoe`),
    B(2, `{0} offers {1} of "{a}" a swig of brown liquor. It was poisoned. "Sorry," says {0}. Not sorry.`, [0], [1], `Poisoned by their own ally {0}`),
    B(2, `{0} pushes {1} of "{a}" into a still green pond. "Nothing personal."`, [0], [1], `Brain-eating amoeba (shoved by their ally {0})`),
    B(2, `{0} takes {1}'s gas mask in the middle of a toxic fog. {1} is an ally no more.`, [0], [1], `Left without a gas mask by their ally {0}`),
    B(2, `{0} stabs {1} of "{a}" in the back, which is where a good alliance keeps its knives.`, [0], [1], `Stabbed in the back by their ally {0}`),
    B(3, `{0} and {1} turn on {2} of "{a}" and bury them in an irradiated pit.`, [0, 1], [2], `Betrayed and buried by their allies {0} and {1}`),
  ];

  /* ---------------------------------------------------------------- DAY ONLY */
  const dayOnly = [
    N(1, `{0} stands on a hill and yells "I AM THE KING OF THIS ARENA."`),
    N(1, `{0} spends all morning searching for water and finds a puddle. A glorious puddle.`),
    N(1, `{0} sunbathes on a rock and gets a spectacular sunburn.`),
    N(1, `{0} yells the names of other tributes at the sky to intimidate them. It does not work.`),
    N(1, `{0} wades into a river to catch fish, catches a boot, and calls it a day.`),
    N(1, `{0} tries to fight a bush. Wins. The bush was not a threat.`),
    N(1, `{0} gives their feline familiar a pep talk before a hunt. The cat just licks itself.`),
    N(1, `{0} tries to build a boat from a log and two shoes. It floats for six whole seconds.`),
    N(1, `{0} hunts all day and returns with a single, deeply disappointing mushroom.`),
    N(2, `{0} and {1} take a "Selfie with a Butterfly" and instantly regret getting that close.`),
    N(2, `{0} steals {1}'s really good shoe while they nap. {1} is furious but too tired to chase.`),
    N(2, `{0} tries to recruit {1} into an alliance. {1} says no. They are still friends. Mostly.`),
    D(`{0} walks into a clearing full of beautiful, glowing flowers. They are not flowers. They are traps.`, `Carnivorous flower field`),
    D(`{0} tries to jump a river on a dare from a squirrel. The squirrel did not mean it.`, `Failed a squirrel-dared river jump`),
    D(`{0} is stung by a swarm of bees as they steal the honey, and shouts "WORTH IT" before collapsing.`, `Bee stings (worth it)`),
    D(`{0} drinks white liquor in the midday sun and passes out on a bed of poisonous nettles.`, `Drunk nap on poisonous nettles`),
    K(2, `{0} throws a net over {1} and drags them into a field of poisonous flowers.`, [0], [1], `Dragged into poisonous flowers by {0}`),
    K(2, `{0} lures {1} into a tree full of killer butterflies, then runs.`, [0], [1], `Left for the killer butterflies by {0}`),
    K(2, `{0} reasons with {1} and then clobbers them with a brick.`, [0], [1], `Bricked, after a polite conversation with {0}`),
    K(3, `{0} and {1} chase {2} straight into a patch of killer butterflies.`, [0, 1], [2], `Chased into killer butterflies by {0} and {1}`),
  ];

  /* ---------------------------------------------------------------- NIGHT ONLY */
  const nightOnly = [
    N(1, `{0} stays up all night whispering "please don't land on me" to a moth.`),
    N(1, `{0} stares at the moon and wonders why they volunteered. They did not volunteer.`),
    N(1, `{0} cries quietly in a hollow log and feels a little better.`),
    N(1, `{0} rehearses a victory speech into a potted fern. There is no potted fern. They're talking to a rock.`),
    N(1, `{0} huddles with a feline familiar for warmth. The cat tolerates this.`),
    N(1, `{0} hears glowing wings in the dark, quietly extinguishes their fire, and holds their breath until dawn.`),
    N(1, `{0} drinks brown liquor alone by the fire and thinks about their choices.`),
    N(1, `{0} sleeps peacefully with a brick under their head and a smile on their face.`),
    N(2, `{0} and {1} take turns keeping watch. {1} falls asleep within four minutes.`),
    N(2, `{0} and {1} stay up talking about home. It gets weirdly emotional.`),
    N(3, `{0}, {1} and {2} tell each other scary stories about killer butterflies. Nobody sleeps.`),
    D(`{0} sleepwalks into a ravine.`, `Sleepwalked off a cliff`),
    D(`{0} falls asleep next to a pretty glowing flower. It was not pretty. It was a gas.`, `Poisonous night-blooming flower`),
    D(`{0} falls asleep and a swarm of killer butterflies finds them.`, `Killer butterflies (found asleep)`),
    D(`{0} is carried off in the night by an extremely determined line of ants.`, `Carried off by ants`),
    D(`{0} drinks white liquor to stay warm, falls asleep in the river, and does not wake up.`, `Drunken river nap`),
    K(2, `{0} cuts the ropes on {1}'s hammock. It's a very long drop.`, [0], [1], `Dropped from a hammock by {0}`),
    K(2, `{0} sneaks up on {1}'s camp and drops a brick on them while they sleep.`, [0], [1], `Bricked in their sleep by {0}`),
    K(2, `{0} smothers {1} with a sleeping bag in the night.`, [0], [1], `Smothered by {0}`),
    K(3, `{0} and {1} hold {2} under the river's surface until {2} stops struggling.`, [0, 1], [2], `Drowned by {0} and {1}`),
  ];

  /* ---------------------------------------------------------------- CORNUCOPIA FEAST */
  const feast = [
    N(1, `{0} grabs a crate of ibuprofen. They are set for the whole games.`),
    N(1, `{0} snatches a gas mask from the feast table and puts it on immediately.`),
    D(`{0} grabs a tempting canister at the feast. It was radon. It is always radon.`, `Radon exposure (feast canister)`),
    N(1, `{0} stuffs their pockets with bread rolls from the feast table.`),
    N(1, `{0} grabs a bag of supplies and a mystery bottle, and bolts.`),
    N(1, `{0} eats an entire wheel of cheese before anyone else arrives. No regrets.`),
    N(1, `{0} grabs a medical kit. It contains one bandage and a very small bottle of white liquor.`),
    N(1, `{0} snatches a feline familiar from the feast table and runs. The cat is thrilled.`),
    N(1, `{0} grabs the last really good shoe. A matching pair at last.`),
    N(2, `{0} and {1} both reach for the last bottle of brown liquor. They share, begrudgingly.`),
    D(`{0} drinks half a barrel of white liquor in the first minute and falls over a table.`, `Drunken face-plant at the feast table`),
    D(`{0} eats the entire sample platter. The sample platter is a trap, laced with poison berries.`, `Poisoned feast sample platter`),
    D(`{0} falls into the open fire pit while trying to cook a rabbit at the feast.`, `Fell into the feast fire pit`),
    K(2, `{0} stabs {1} with a carving knife.`, [0], [1], `Carving knife, wielded by {0}`),
    K(2, `{0} bashes {1} with a brick from the feast display.`, [0], [1], `Feast-table bricking by {0}`),
    K(2, `{0} pushes {1} into a barrel of white liquor, and {1} does not come back up.`, [0], [1], `Drowned in a barrel of white liquor ({0})`),
    K(3, `{0} and {1} corner {2} at the carving station. It was not a good place to be cornered.`, [0, 1], [2], `Cornered at the feast by {0} and {1}`),
  ];

  const feastIntros = [
    `The Gamemakers announce a feast at the Cornucopia. "Each of you has a need, and it will be filled," they say. It is a buffet. It is a trap. It is a buffet and a trap.`,
    `A booming voice echoes across the arena: "Attention, tributes! There will be a feast at the Cornucopia at dawn. Bring an appetite. And a weapon."`,
    `The Gamemakers invite the tributes to a "Members-Only Feast" at the Cornucopia. Nobody is a member. Everyone attends anyway.`,
  ];

  /* ---------------------------------------------------------------- SPONSOR GIFTS ({0} receives) */
  const gifts = [
    `A sponsor sends {0} a gas mask. {0} puts it on and refuses to take it off.`,
    `A silver parachute lands beside {0}. Inside: an absurdly large bottle of ibuprofen. The label reads "FOR ALL OCCASIONS".`,
    `A sponsor sends {0} a tank of radon. Nobody knows why. Someone out there hates {0}.`,
    `A sponsor sends {0} a Geiger counter. It clicks. {0} wishes it wouldn't.`,
    `A sponsor sends {0} iodine tablets with a note: "You'll need these." {0} is suddenly worried.`,
    `A sponsor sends {0} a sealed bottle of clean water. {0} sobs, because it is clean.`,
    `A silver parachute floats down to {0}. Inside: a loaf of fresh bread. A hero is born.`,
    `A silver parachute lands beside {0}. Inside: a bottle of clean water. {0} weeps openly.`,
    `A silver parachute drifts down to {0}. Inside: medicine. It works. {0} feels fantastic.`,
    `A sponsor sends {0} a bottle of white liquor with a note: "You need this." They absolutely do.`,
    `A sponsor sends {0} a bottle of brown liquor with a note: "For when it gets bad." It is already bad.`,
    `A sponsor sends {0} a brick. Just a brick. Someone out there really believes in them.`,
    `A sponsor sends {0} the other really good shoe. At last: a matching pair.`,
    `A sponsor sends {0} a feline familiar, who immediately sits on their head and refuses to move.`,
    `A silver parachute lands in front of {0}. Inside: a very sharp knife. And a bow tie. The bow tie is optional.`,
    `A sponsor sends {0} a note: "You're doing great sweetie. Love, a stranger." {0} cries.`,
    `A sponsor sends {0} a tiny violin. {0} understands the message.`,
    `A sponsor sends {0} a fire starter kit. {0} is moved, and also finally warm.`,
    `A silver parachute drifts down to {0}. Inside: a single sock. A mystery. A gift. A single sock.`,
    `A sponsor sends {0} a sleeping bag so soft that {0} sleeps for fourteen hours straight.`,
    `A sponsor sends {0} a map of the poisonous plants of the arena. It is color-coded. It is perfect.`,
    `A sponsor sends {0} a net with a note: "For the butterflies." {0} sighs in relief.`,
  ];

  /* ---------------------------------------------------------------- DISASTERS */
  const disasters = [
    {
      id: `wildfire`, kind: `disaster`, title: `Wildfire`,
      intro: `The Gamemakers set the forest ablaze. Walls of flame roar through the trees, driving the tributes before them.`,
      min: 0.4, max: 0.8, rate: 0.3, cap: 4,
      deaths: [
        [`{0} is cornered by the flames and does not make it out.`, `Burned in the wildfire`],
        [`{0} runs directly into a burning tree.`, `Ran into a burning tree`],
        [`{0} inhales too much smoke while yelling "THIS ISN'T FAIR!"`, `Smoke inhalation (and unfairness)`],
        [`{0} tries to put out the fire with white liquor. It was a poor decision.`, `Used white liquor to fight a fire`],
      ],
      survives: [
        `{0} dives into a river and stays there, dripping with dignity.`,
        `{0} escapes by wrapping up in a wet sleeping bag.`,
        `{0} leaps through a burning hoop of branches and honestly looks pretty cool doing it.`,
        `{0} sprints out of the fire, singed, eyebrowless, alive.`,
        `{0} carries their feline familiar to safety. The cat is furious about it.`,
      ],
      outro: `The fire burns out. The arena smells like a barbecue. Nobody is hungry.`,
    },
    {
      id: `flood`, kind: `disaster`, title: `Flash Flood`,
      intro: `The Gamemakers break the dam. A wall of brown water thunders through the arena.`,
      min: 0.5, max: 0.9, rate: 0.28, cap: 4,
      deaths: [
        [`{0} is swept away by the tide and is last seen floating past the Cornucopia.`, `Swept away by the flash flood`],
        [`{0} is pinned under a log and drowns.`, `Drowned under a log in the flood`],
        [`{0} tries to swim to safety with a brick in each hand. Gravity wins.`, `Drowned holding two bricks`],
      ],
      survives: [
        `{0} climbs a tree and waits it out.`,
        `{0} floats serenely on a barrel of brown liquor.`,
        `{0} surfs the flood on a plank and whoops all the way down.`,
        `{0} gets very, very wet and is very, very fine.`,
      ],
      outro: `The water drains slowly. Somewhere, a fish is sitting in a tree.`,
    },
    {
      id: `pollen`, kind: `disaster`, title: `Toxic Pollen Storm`,
      intro: `Every poisonous plant in the arena blooms at once. A thick yellow cloud of pollen rolls across the forest. It smells wonderful. That's the worst part.`,
      min: 0.4, max: 0.7, rate: 0.3, cap: 3,
      deaths: [
        [`{0} breathes too deeply of the pollen and falls over mid-sentence.`, `Poisoned by toxic pollen`],
        [`{0} thinks it's "just allergies" and walks straight through the thick of it.`, `Mistook toxic pollen for allergies`],
        [`{0} gets cornered by the cloud in a dead-end canyon.`, `Cornered by toxic pollen`],
      ],
      survives: [
        `{0} ties a shirt over their face and heroically pushes through the cloud.`,
        `{0} holds their breath for six minutes. A new personal best.`,
        `{0} hides in a cave and waits for the pollen to pass.`,
        `{0} sneezes forty-one times and is fine.`,
      ],
      outro: `The pollen settles. Everything is covered in a shimmering golden powder. Nobody touches anything.`,
    },
    {
      id: `moonshine`, kind: `disaster`, title: `Moonshine Monsoon`,
      intro: `The Gamemakers open the clouds, and it begins to rain white liquor. Heavy, cold, 190-proof liquor. The tributes look up with their mouths open.`,
      min: 0.6, max: 1.0, rate: 0.25, cap: 4,
      deaths: [
        [`{0} drinks the rain straight from the sky and lies down in the mud, extremely happy, extremely done.`, `Died of an excess of white liquor rain`],
        [`{0} slips in the liquor mud and cracks their head on a brick.`, `Slipped in liquor mud, hit a brick`],
        [`{0} decides to light a cigarette in the moonshine rain. Poof.`, `Lit a flame in a liquor storm`],
      ],
      survives: [
        `{0} catches the rain in a hat and calls it dinner.`,
        `{0} gets completely hammered and sings to a tree.`,
        `{0} falls asleep in a puddle of white liquor and wakes up with no regrets and a headache.`,
        `{0} dances in the rain, uncaring, joyful, drunk.`,
        `{0} hides under a really good shoe. It works surprisingly well.`,
      ],
      outro: `The rain stops. The arena smells like a distillery. Every living thing is deeply, deeply confused.`,
    },
    {
      id: `quake`, kind: `disaster`, title: `Earthquake`,
      intro: `The ground trembles. Cracks race across the arena floor, and sinkholes open beneath the trees.`,
      min: 0.4, max: 0.8, rate: 0.3, cap: 3,
      deaths: [
        [`{0} falls into a sinkhole. A long, sad scream follows.`, `Fell into a sinkhole`],
        [`{0} is crushed by a falling boulder.`, `Crushed by a boulder`],
        [`{0} is buried when a cliff comes down.`, `Buried by a landslide`],
      ],
      survives: [
        `{0} clings to a tree and rides out the shaking.`,
        `{0} leaps over a widening crack with a graceful, slightly panicked jump.`,
        `{0} is thrown clear by the quake and lands in a pile of leaves.`,
        `{0} rolls under a log and stays there until the rumbling stops.`,
      ],
      outro: `The ground stops shaking. A distant tree finishes falling over.`,
    },
    {
      id: `leak`, kind: `disaster`, title: `Radiation Leak`,
      intro: `A siren wails. Barrels crack open across the arena and a sickly green glow spreads over the ground. The Geiger counters begin to scream.`,
      min: 0.5, max: 0.9, rate: 0.3, cap: 4,
      deaths: [
        [`{0} is caught in the glow with no gas mask and no plan.`, `Radiation poisoning (radiation leak)`],
        [`{0} runs the wrong way, directly toward the leak.`, `Ran toward the radiation leak`],
        [`{0} tries to carry a leaking barrel to safety. It is not safety.`, `Radiation poisoning (carried a leaking barrel)`],
      ],
      survives: [
        `{0} pulls on a gas mask and walks through the glow like they own the place.`,
        `{0} takes a handful of ibuprofen and a very deep breath and runs.`,
        `{0} hides inside an old terrarium. It is somehow lead-lined.`,
        `{0} escapes with only their eyebrows missing.`,
        `{0} wraps themself in a shower curtain and sprints. It helps. Probably.`,
      ],
      outro: `The leak seals itself. The glow lingers. The ground is slightly warm.`,
    },
    {
      id: `surge`, kind: `disaster`, title: `Stagnant Surge`,
      intro: `Every still pond in the arena swells over its banks. The water is warm. The water is green. The water is alive.`,
      min: 0.4, max: 0.8, rate: 0.3, cap: 4,
      deaths: [
        [`{0} gets a mouthful of the surge up their nose.`, `Brain-eating amoeba (stagnant surge)`],
        [`{0} goes under for just a second. A second is all it takes.`, `Brain-eating amoeba (went under for a second)`],
        [`{0} laughs, floats on their back, and takes a big gulp of the surge. They stop laughing eventually.`, `Brain-eating amoeba (floated on their back)`],
      ],
      survives: [
        `{0} holds their nose and their breath for the entire surge.`,
        `{0} climbs a tree and refuses to look down.`,
        `{0} wears a gas mask over their face. It works surprisingly well as a snorkel.`,
        `{0} surfs the surge on a plank and is fine. Do not do this.`,
      ],
      outro: `The water recedes, leaving green slime everywhere. Nobody touches the slime.`,
    },

  ];

  /* ---------------------------------------------------------------- MUTTS */
  const mutts = [
    {
      id: `razorwings`, kind: `mutt`, title: `Razorwing Swarm`,
      intro: `The Gamemakers release the pavilion's butterflies, long since mutated by the radiation. Not the pretty ones. The ones with the razor wings. Thousands of them, drifting out of the trees, beautiful and hungry.`,
      min: 0.4, max: 0.8, rate: 0.35, cap: 4,
      deaths: [
        [`{0} is enveloped by a cloud of razorwing butterflies. It is the last thing they ever see, and it is pretty.`, `Razorwing butterfly swarm`],
        [`{0} locks eyes with a razorwing and cannot look away in time.`, `Hypnotized by a razorwing butterfly`],
        [`{0} tries to fight the swarm with a brick. It did not go well.`, `Fought a butterfly swarm with a brick`],
      ],
      survives: [
        `{0} dives into a river and holds their breath until the butterflies lose interest.`,
        `{0} climbs a tree. The butterflies circle below like very elegant sharks.`,
        `{0} puts out the fire and hides in the smoke. Butterflies hate smoke.`,
        `{0} throws their brown liquor at the swarm. The butterflies pass out. A new strategy is discovered.`,
      ],
      outro: `The surviving butterflies flutter away, leaving behind a few sparkly scales and a lot of anxiety.`,
    },
    {
      id: `caterpillars`, kind: `mutt`, title: `Very Hungry Mutts`,
      intro: `The Gamemakers unleash genetically modified caterpillars the size of buses. They have not eaten since Saturday. It is Wednesday.`,
      min: 0.4, max: 0.8, rate: 0.3, cap: 4,
      deaths: [
        [`{0} is eaten alive, leaving only a leaf-shaped hole in the shrubbery.`, `Eaten by a mutant caterpillar`],
        [`{0} becomes a Saturday snack: one slice of cake, one pickle, one cupcake, and one tribute.`, `Became a Very Hungry Caterpillar's snack`],
        [`{0} is mistaken for a particularly delicious leaf.`, `Mistaken for a leaf and eaten`],
      ],
      survives: [
        `{0} climbs a tree. The caterpillar cannot follow; it is too busy with the leaves.`,
        `{0} throws a cabbage as a distraction and sprints away.`,
        `{0} befriends a mutt caterpillar by singing it a lullaby.`,
        `{0} hides inside a hollow log and waits for the munching to end.`,
      ],
      outro: `The caterpillars curl up for a nap, bellies visibly rounder.`,
    },
    {
      id: `cats`, kind: `mutt`, title: `Feline Familiars`,
      intro: `A hundred feline familiars pour out of the trees. They are fluffy. They are adorable. They have the eyes of the fallen tributes. They have been waiting.`,
      min: 0.4, max: 0.7, rate: 0.3, cap: 3,
      deaths: [
        [`{0} stops to pet a feline familiar. It is a trap. Many, many more feline familiars appear.`, `Mauled by feline familiars (stopped to pet one)`],
        [`{0} is smothered by an affectionate pile of fluffy mutt cats.`, `Smothered by a pile of mutt cats`],
        [`{0} drops their guard to scratch one behind the ear and is never seen again.`, `Lured by a mutt cat's cuteness`],
      ],
      survives: [
        `{0} throws a yarn ball. The mutt cats are fully distracted for hours.`,
        `{0} holds absolutely still. Nothing dares move. Nothing blinks. Nothing.`,
        `{0} hisses back. The cats respect it.`,
        `{0} pulls out their own feline familiar. The two parties circle each other and, without a word, back away.`,
      ],
      outro: `The feline familiars melt back into the trees, tails twitching, judging everyone.`,
    },
    {
      id: `trackers`, kind: `mutt`, title: `Tracker Jackers`,
      intro: `Tracker jackers! Swarms of hallucinogenic, venomous wasps descend on the tributes. Their sting causes vivid visions.`,
      min: 0.4, max: 0.8, rate: 0.3, cap: 4,
      deaths: [
        [`{0} is stung, hallucinates a free buffet, and walks off a cliff.`, `Hallucinated off a cliff (tracker jacker venom)`],
        [`{0} is stung and sees a loved one holding a tray of cookies. The tray is a swamp.`, `Followed a hallucinated cookie tray into a swamp`],
        [`{0} is stung so many times they simply have to sit down forever.`, `Tracker jacker overdose`],
      ],
      survives: [
        `{0} is stung and spends an hour talking to a bush. The bush gives great advice.`,
        `{0} is stung and hallucinates a giant brick. It's a brick.`,
        `{0} is stung and gets the best nap of their life.`,
        `{0} is stung and begins to dance. They stop, but only because the dance ended.`,
      ],
      outro: `The tracker jackers drift off, buzzing something that sounds like a jingle.`,
    },
    {
      id: `vines`, kind: `mutt`, title: `Strangler Vines`,
      intro: `The Gamemakers have bred the arena's poisonous plants with something else. The vines are moving. The vines are hungry. The vines are sorry.`,
      min: 0.3, max: 0.7, rate: 0.35, cap: 3,
      deaths: [
        [`{0} is snatched by a vine mid-sentence and never finishes the sentence.`, `Strangled by a mutant vine`],
        [`{0} tries to argue with a vine. It does not take feedback.`, `Argued with a mutant vine`],
        [`{0} is lifted into the canopy and slowly digested by a very large, very green flower.`, `Digested by a giant carnivorous flower`],
      ],
      survives: [
        `{0} chops through the vines with a machete and runs.`,
        `{0} sets fire to the vines and gets away, singed but alive.`,
        `{0} gets completely wrapped up, plays dead, and is unceremoniously dropped.`,
        `{0} offers the vine a bottle of white liquor. The vine passes out.`,
      ],
      outro: `The vines retreat into the soil. A flower nearby burps.`,
    },
  ];

  const memos = [
    `Gamemaker memo: "The pavilion has been abandoned for years. We recommend not touching anything. Touch everything."`,
    `Gamemaker memo: "Reminder: still water is not your friend. Neither is the green glow. Neither are your friends."`,
    `Gamemaker memo: "Ibuprofen is not a food group. Please stop treating it as one."`,
    `Gamemaker memo: "The radon is not for sale. The radon is not for anything."`,
    `Gamemaker memo: "A gas mask does not make you invincible. It makes you look cool."`,
    `Gamemaker memo: "The alliances have been duly noted. The betrayals have been eagerly anticipated."`,
    `Gamemaker memo: "Please stop feeding the tributes. They are part of the exhibit."`,
    `Gamemaker memo: "The butterflies are not pets. They are assets."`,
    `Gamemaker memo: "Reminder: do not pet the butterflies. Do not pet the plants. Do not pet the cats. Do not pet."`,
    `Gamemaker memo: "Whoever keeps naming the cats: stop."`,
    `Gamemaker memo: "The white liquor supply has been increased. For reasons."`,
    `Gamemaker memo: "A butterfly has gone missing. It is very important. Please do not look under the ferns."`,
    `Gamemaker memo: "Brown liquor is not a replacement for water. It is a replacement for judgment."`,
    `Gamemaker memo: "The tribute with the really good shoe is the most dangerous tribute. We have decided this."`,
    `Gamemaker memo: "To the tribute who keeps hugging the poison ivy: it's fine. Continue."`,
    `Gamemaker memo: "Sponsors, please remember: bricks are not a gift. They are an investment."`,
    `Gamemaker memo: "Spoiler alert: the berries are poisonous. All of them. We lied."`,
    `Gamemaker memo: "Whoever keeps making tea: the leaves are not mint."`,
    `Gamemaker memo: "A reminder that every butterfly is a potential witness."`,
    `Gamemaker memo: "The Capitol would like to apologize for the fire. The Capitol would also like to do it again."`,
  ];

  const winnerLines = [
    `emerges from the arena, covered in scratches and glitter, clutching a really good shoe, victorious.`,
    `walks out of the arena as the last tribute standing, and immediately asks for a drink.`,
    `is crowned the victor, and a lone butterfly lands on their shoulder in what seems like respect, or a threat.`,
    `survives it all, and as a reward is allowed to keep the brick.`,
  ];

  global.BPG_EVENTS = {
    bloodbath: bloodbath.concat(classic),
    day: any.concat(classic, hazards, alliances, dayOnly),
    night: any.concat(classic, hazards, alliances, nightOnly),
    feast: feast.concat(classic),
    feastIntros,
    gifts,
    allianceNames: [
      `The Careers`, `The Rad Pack`, `The Ibuprofen Gang`, `The Gas Mask Bandits`, `The Brick House`,
      `The Good Sole Alliance`, `Team Sober`, `The Glow Crew`, `The Brown Liquor Brigade`, `The Hydrated Few`,
      `The Amoeba Avoiders`, `The Feline Fellowship`, `The Radon Rangers`, `The Last Shoe`, `Hangover Squad`,
      `The Pavilion Preservation Society`,
    ],
    disasters,
    mutts,
    memos,
    winnerLines,
    zones: [
      `Luxury`, `Masonry`, `Technology`, `Fishing`, `Power`, `Transportation`,
      `Lumber`, `Textiles`, `Grain`, `Livestock`, `Agriculture`, `Mining`,
    ],
    sampleNames: [
      `Katniss`, `Peeta`, `Haymitch`, `Effie`, `Finnick`, `Cato`, `Clove`, `Glimmer`,
      `Marvel`, `Rue`, `Foxface`, `Thresh`, `Johanna`, `Beetee`, `Wiress`, `Mags`,
      `Seeder`, `Chaff`, `Cecelia`, `Gloss`, `Brutus`, `Enobaria`, `Plutarch`, `Cinna`,
    ],
  };
})(window);
